type: edu
custom_name: stage2
files:
- name: tests.py
  visible: false
  text: |
    from hstest.stage_test import StageTest
    from hstest.test_case import TestCase
    from hstest.check_result import CheckResult

    import sys
    if sys.platform.startswith("win"):
        import _locale
        # pylint: disable=protected-access
        _locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])

    CheckResult.correct = lambda: CheckResult(True, '')
    CheckResult.wrong = lambda feedback: CheckResult(False, feedback)


    class TranslatorTest(StageTest):
        def generate(self):
            return [
                TestCase(stdin='fr\nhello\n'),
            ]

        def check(self, reply, attach):
            if '200 OK' not in reply:
                return CheckResult.wrong("There isn't internet connection identificator.")

            print(reply.count('['))
            print('Translation' in reply)

            if reply.count('[') >= 2 and 'Translation' in reply:
                return CheckResult.correct()

            return CheckResult.wrong("Try to print lists of translations in both "
                                     "stages or not to delete first word 'Translation' from it")


    if __name__ == '__main__':
        TranslatorTest('translator.translator').run_tests()
  learner_created: false
- name: translator/translator.py
  visible: true
  text: |
    print('Hello, World!')
  learner_created: false
- name: translator/__init__.py
  visible: true
  learner_created: true
feedback_link: https://hyperskill.org/projects/99/stages/544/implement
status: Failed
feedback:
  message: |-
    Exception in test #1

    Traceback (most recent call last):
      File "translator.py", line 34, in <module>
        Translator().main()
      File "translator.py", line 22, in main
        response = requests.get(Translator.form_request(self), headers={'User-Agent': Translator.user_agent})
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/english-french/hello (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B2152252E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

    Please find below the output of your program during this failed test.

    ---

    You chose "fr" as a language to translate "hello".
  time: Sun, 25 Oct 2020 10:21:58 UTC
record: -1
